# Generated by Django 3.2.8 on 2021-11-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultureapp', '0002_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('service', models.ManyToManyField(blank=True, null=True, related_name='services', to='cultureapp.services')),
            ],
        ),
    ]
