# Generated by Django 3.2.8 on 2021-11-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultureapp', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='visit_type',
            field=models.CharField(choices=[('', 'Choose Visit Type'), ('One Person', 'One Person'), ('Two-Three People', 'Two-Three People'), ('Family Vacation', 'Family Vacation'), ('Educational ', 'Educational '), ('Staff Get Together', 'Staff Get Together'), ('Filming', 'Filming')], default=0, max_length=50),
        ),
    ]
